### ISSUE TITLE
Stats Page doesn't Display Graphs Anymore

### ISSUE THREAD

**Issue by veqqq** [lobsters/lobsters#1562]
https://lobste.rs/stats

Everything just says:  No data 

This has been around for perhaps a week.

**Comment by veqqq** [comment]
Yesterday this worked again, but... Today it's back to "no data".

**Comment by pushcx** [comment]
bf2d3b45

**Comment by pushcx** [comment]
Spent a few minutes investigating this on today's [office hours stream](https://push.cx/stream/2025-05-22). It's not a timezone issue (surprise!), it's the cache size. Rack::Attack has to write multiple entries for each unique IP it sees, so its usage is evicting other entries. I nudged the max cache size up to 2 GB (we have 181 GB free on prod), we'll see in a day or two if this is ~fixed by that.

Potential other fixes:
 * Move rack::attack to its own cache
 * Move graphs to its own cache (you get cache, you get a cache...)
 * Run fill job more often
 * Have a cache miss enqueue the job (but dogpiling)

**Comment by zipy124** [comment]
This still happens, usually around the 1st of the month. All graphs but 'Active users by month' are now up as of the 4th, but this seems to be a regular occurrence.
